blacklist-worlds:
  - "example world"
blacklist-worldguard-regions:
  - "exampleName"
glue:
  name: "name"
  lore:
    - "lore"
    - "lore2"
  type: "minecraft:gray_dye"
  effect-area: 4
  full-repair: true